Product.create(name: "apple", price: 2)
Product.create(name: "orange", price: 2)
Product.create(name: "banana", price: 3)
Product.create(name: "lemon", price: 1)
Product.create(name: "avocado", price: 1)